#!/usr/bin/env python3
import math
import os
from datetime import datetime
import json
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Depends, Query
from sqlmodel import Session, create_engine, select, SQLModel, delete
from fastapi.middleware.cors import CORSMiddleware

from models import (
    Exercise,
    MuscleState,
    WorkoutSession,
    SetLog,
    WorkoutSummary,
    FATIGUE_LIMIT,
    DECAY_K,
)

app = FastAPI(
    title="Hypertrophy Planner API",
    version="1.0.0",
    description="Smart workout tracker with fatigue-based recovery management",
)

# CORS for local frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Database setup
os.makedirs("./data", exist_ok=True)
sqlite_url = "sqlite:///./data/gym.db"
engine = create_engine(
    sqlite_url, echo=False, connect_args={"check_same_thread": False}
)


def get_session():
    with Session(engine) as session:
        yield session


@app.on_event("startup")
def on_startup():
    """Initialize database tables."""
    SQLModel.metadata.create_all(engine)


# --- Helper Functions ---


def get_decayed_fatigue(state: MuscleState) -> float:
    """Calculate current fatigue with exponential decay."""
    if not state:
        return 0.0
    now = datetime.now()
    days_passed = (now - state.last_updated).total_seconds() / 86400.0
    return max(0.0, state.current_fatigue * math.exp(-DECAY_K * days_passed))


def calculate_set_fatigue(exercise: Exercise, log: SetLog) -> float:
    """
    Calculate fatigue generated by a single set based on effort, not absolute tonnage.
    """
    # Base effort: If RPE isn't provided, assume a moderate-hard set (RPE 7)
    intensity_factor = (log.rpe / 10.0) if log.rpe else 0.7

    # Optional: Slightly scale up fatigue for higher rep ranges (metabolic stress)
    # e.g., 20 reps generates 20% more local fatigue than 5 reps
    rep_multiplier = 1.0 + (log.reps * 0.01)

    # Fatigue = Base Exercise Rating × Effort × Rep Modifier
    return exercise.fatigue_rating * intensity_factor * rep_multiplier


def get_muscle_status_with_decay(db: Session) -> dict:
    """Get all muscle groups with decayed fatigue values."""
    states = db.exec(select(MuscleState)).all()
    return {s.muscle_group: round(get_decayed_fatigue(s), 2) for s in states}


# --- Exercise Endpoints ---


@app.get("/exercises", tags=["Exercises"])
def list_exercises(
    db: Session = Depends(get_session),
    muscle_group: Optional[str] = Query(None),
):
    """List all exercises, optionally filtered by muscle group."""
    query = select(Exercise)
    if muscle_group:
        query = query.where(
            (Exercise.primary_muscle == muscle_group)
            | (Exercise.secondary_muscle == muscle_group)
        )
    return db.exec(query.order_by(Exercise.name)).all()


@app.get("/exercises/{exercise_id}", tags=["Exercises"])
def get_exercise(exercise_id: int, db: Session = Depends(get_session)):
    """Get a specific exercise by ID."""
    ex = db.get(Exercise, exercise_id)
    if not ex:
        raise HTTPException(status_code=404, detail="Exercise not found")
    return ex


@app.post("/exercises", tags=["Exercises"])
def create_exercise(ex: Exercise, db: Session = Depends(get_session)):
    """Create a new exercise."""
    if ex.fatigue_rating < 0.1 or ex.fatigue_rating > 10.0:
        raise HTTPException(
            status_code=422,
            detail="Fatigue rating must be between 0.1 and 10.0",
        )
    db.add(ex)
    db.commit()
    db.refresh(ex)
    return ex


@app.put("/exercises/{exercise_id}", tags=["Exercises"])
def update_exercise(
    exercise_id: int,
    updated_ex: Exercise,
    db: Session = Depends(get_session),
):
    """Update an existing exercise."""
    ex = db.get(Exercise, exercise_id)
    if not ex:
        raise HTTPException(status_code=404, detail="Exercise not found")

    ex.name = updated_ex.name
    ex.primary_muscle = updated_ex.primary_muscle
    ex.secondary_muscle = updated_ex.secondary_muscle
    ex.fatigue_rating = updated_ex.fatigue_rating
    ex.notes = updated_ex.notes

    db.add(ex)
    db.commit()
    db.refresh(ex)
    return ex


@app.delete("/exercises/{exercise_id}", tags=["Exercises"])
def delete_exercise(exercise_id: int, db: Session = Depends(get_session)):
    """Delete an exercise by ID."""
    ex = db.get(Exercise, exercise_id)
    if not ex:
        raise HTTPException(status_code=404, detail="Exercise not found")

    # Delete all set logs referencing this exercise
    db.exec(delete(SetLog).where(SetLog.exercise_id == exercise_id))
    db.delete(ex)
    db.commit()
    return {"deleted": exercise_id, "message": "Exercise and associated logs deleted"}


# --- Status Endpoints ---


@app.get("/status", tags=["Status"])
def get_muscle_status(db: Session = Depends(get_session)):
    """
    Get current fatigue for all muscle groups with real-time decay applied.
    Returns {"Chest": 3.45, "Back": 2.1, ...}
    """
    return get_muscle_status_with_decay(db)


@app.get("/status/{muscle_group}", tags=["Status"])
def get_muscle_status_single(muscle_group: str, db: Session = Depends(get_session)):
    """Get fatigue for a specific muscle group."""
    state = db.get(MuscleState, muscle_group)
    if not state:
        return {"muscle_group": muscle_group, "fatigue": 0.0, "status": "fresh"}

    decayed = get_decayed_fatigue(state)
    status = "red-zoned" if decayed >= FATIGUE_LIMIT else "available"

    return {
        "muscle_group": muscle_group,
        "fatigue": round(decayed, 2),
        "status": status,
        "limit": FATIGUE_LIMIT,
    }


@app.post("/status/reset/{muscle_group}", tags=["Status"])
def reset_muscle_fatigue(muscle_group: str, db: Session = Depends(get_session)):
    """Reset fatigue for a specific muscle group (for recovery/deload weeks)."""
    state = db.get(MuscleState, muscle_group)
    if not state:
        return {"message": f"No fatigue record for {muscle_group}"}

    state.current_fatigue = 0.0
    state.last_updated = datetime.now()
    db.add(state)
    db.commit()
    return {"reset": muscle_group, "fatigue": 0.0}


# --- Workout Session Endpoints ---


@app.post("/session/start", tags=["Session"])
def start_session(db: Session = Depends(get_session)):
    """Start a new workout session. Only one active session allowed."""
    active = db.exec(
        select(WorkoutSession).where(WorkoutSession.status == "active")
    ).first()
    if active:
        return {
            "message": "Active session already exists",
            "session": active,
        }

    new_session = WorkoutSession(status="draft")
    db.add(new_session)
    db.commit()
    db.refresh(new_session)
    return new_session


@app.get("/session/current", tags=["Session"])
def get_current_session(db: Session = Depends(get_session)):
    """Get the current active session."""
    active = db.exec(
        select(WorkoutSession).where(WorkoutSession.status == "active")
    ).first()
    if not active:
        raise HTTPException(status_code=404, detail="No active session")
    return active


@app.post("/session/draft", tags=["Session"])
def save_draft(template: List[dict], db: Session = Depends(get_session)):
    """Save a workout plan as a draft."""
    # Check if draft already exists
    existing = db.exec(
        select(WorkoutSession).where(WorkoutSession.status == "draft")
    ).first()

    session = existing or WorkoutSession(status="draft")
    session.planned_template = json.dumps(template)
    db.add(session)
    db.commit()
    db.refresh(session)
    return session


@app.post("/session/activate/{session_id}", tags=["Session"])
def activate_session(session_id: int, db: Session = Depends(get_session)):
    """Convert a draft session to active."""
    session = db.get(WorkoutSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if session.status != "draft":
        raise HTTPException(status_code=400, detail="Session is not a draft")

    session.status = "active"
    db.add(session)
    db.commit()
    db.refresh(session)
    return session


@app.delete("/session/draft/{session_id}", tags=["Session"])
def delete_draft(session_id: int, db: Session = Depends(get_session)):
    """Delete a draft session."""
    session = db.get(WorkoutSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if session.status != "draft":
        raise HTTPException(status_code=400, detail="Can only delete draft sessions")

    db.delete(session)
    db.commit()
    return {"deleted": session_id}


@app.post("/session/log-set", tags=["Session"])
def log_set(log: SetLog, db: Session = Depends(get_session)):
    """Log a single set in an active session."""
    # Validate session exists and is active
    session = db.get(WorkoutSession, log.session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if session.status != "active":
        raise HTTPException(status_code=400, detail="Session is not active")

    # Validate exercise exists
    exercise = db.get(Exercise, log.exercise_id)
    if not exercise:
        raise HTTPException(status_code=404, detail="Exercise not found")

    # Validate inputs
    if log.reps < 1 or log.reps > 100:
        raise HTTPException(status_code=422, detail="Reps must be 1-100")
    if log.weight < 0 or log.weight > 10000:
        raise HTTPException(status_code=422, detail="Weight must be 0-10000")
    if log.rpe and (log.rpe < 1 or log.rpe > 10):
        raise HTTPException(status_code=422, detail="RPE must be 1-10")

    db.add(log)
    db.commit()
    db.refresh(log)
    return {"status": "success", "log_id": log.id}


@app.get("/session/{session_id}/logs", tags=["Session"])
def get_session_logs(
    session_id: int,
    db: Session = Depends(get_session),
):
    """Get all set logs for a specific session."""
    session = db.get(WorkoutSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    logs = db.exec(select(SetLog).where(SetLog.session_id == session_id)).all()
    return logs


@app.delete("/session/{session_id}", tags=["Session"])
def delete_session(session_id: int, db: Session = Depends(get_session)):
    """Delete an entire session, its logs, and reverse its lingering fatigue."""
    session = db.get(WorkoutSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    # Fetch all logs for this session
    logs = db.exec(select(SetLog).where(SetLog.session_id == session_id)).all()

    # If the session was already completed, we MUST reverse the fatigue
    if session.status == "completed":
        session_fatigue = {}

        # 1. Re-calculate the raw fatigue this session originally generated
        for log in logs:
            ex = db.get(Exercise, log.exercise_id)
            if not ex:
                continue

            set_fatigue = calculate_set_fatigue(ex, log)
            session_fatigue[ex.primary_muscle] = (
                session_fatigue.get(ex.primary_muscle, 0) + set_fatigue
            )

            if ex.secondary_muscle:
                session_fatigue[ex.secondary_muscle] = session_fatigue.get(
                    ex.secondary_muscle, 0
                ) + (set_fatigue * 0.4)

        # 2. Calculate how much of that fatigue is STILL in the body today
        now = datetime.now()
        days_passed = (
            (now - session.date).total_seconds() / 86400.0 if session.date else 0
        )
        decay_factor = math.exp(-DECAY_K * max(0, days_passed))

        # 3. Subtract the lingering fatigue from the current muscle states
        for muscle, original_fatigue in session_fatigue.items():
            state = db.get(MuscleState, muscle)
            if state:
                lingering_fatigue = original_fatigue * decay_factor

                # Bring state up to 'now', then subtract the lingering amount
                current_decayed = get_decayed_fatigue(state)
                state.current_fatigue = max(0.0, current_decayed - lingering_fatigue)
                state.last_updated = now
                db.add(state)

    # 4. Delete the logs and the session itself
    for log in logs:
        db.delete(log)

    db.delete(session)
    db.commit()

    return {"message": "Session deleted and lingering fatigue reversed"}


@app.delete("/session/{session_id}/logs/{log_id}", tags=["Session"])
def delete_set_log(
    session_id: int,
    log_id: int,
    db: Session = Depends(get_session),
):
    """Delete a single set log (for fixing mistakes)."""
    log = db.get(SetLog, log_id)
    if not log or log.session_id != session_id:
        raise HTTPException(status_code=404, detail="Set log not found")

    db.delete(log)
    db.commit()
    return {"deleted": log_id}


@app.post("/session/finish/{session_id}", tags=["Session"])
def finish_session(
    session_id: int,
    db: Session = Depends(get_session),
):
    """
    Finalize a session and update global muscle fatigue.
    This applies exponential decay to existing fatigue, then adds new fatigue from this session.
    """
    workout = db.get(WorkoutSession, session_id)
    if not workout:
        raise HTTPException(status_code=404, detail="Session not found")
    if workout.status != "active":
        raise HTTPException(status_code=400, detail="Session is already completed")

    # Replace your old logs query with this:
    from sqlmodel import select

    # Fetch logs and exercises together
    statement = (
        select(SetLog, Exercise)
        .join(Exercise, SetLog.exercise_id == Exercise.id)
        .where(SetLog.session_id == session_id)
    )
    results = db.exec(statement).all()

    if not results:
        workout.status = "completed"
        db.add(workout)
        db.commit()
        return {"message": "Empty session completed"}

    session_fatigue = {}
    total_volume = 0.0

    for log, ex in results:
        set_fatigue = calculate_set_fatigue(ex, log)

        session_fatigue[ex.primary_muscle] = (
            session_fatigue.get(ex.primary_muscle, 0) + set_fatigue
        )

        if ex.secondary_muscle:
            session_fatigue[ex.secondary_muscle] = session_fatigue.get(
                ex.secondary_muscle, 0
            ) + (set_fatigue * 0.4)

            total_volume += log.reps * log.weight

    # Update global muscle states with decay + new fatigue
    for muscle, added_fatigue in session_fatigue.items():
        state = db.get(MuscleState, muscle)
        if not state:
            state = MuscleState(muscle_group=muscle, current_fatigue=0.0)
            db.add(state)

        # Decay existing fatigue first, then add session fatigue
        decayed = get_decayed_fatigue(state)
        state.current_fatigue = decayed + added_fatigue
        state.last_updated = datetime.now()
        db.add(state)

    # Mark session complete and calculate duration
    workout.status = "completed"
    if workout.date:
        duration = (datetime.now() - workout.date).total_seconds() / 60
        workout.duration_minutes = max(1, int(duration))
    db.add(workout)
    db.commit()

    return {
        "message": "Workout saved and fatigue updated",
        "session_id": session_id,
        "fatigue_applied": session_fatigue,
        "total_volume": round(total_volume, 2),
    }


# --- Workout History & Analytics ---


@app.post("/session/generate", tags=["Planning"])
def generate_workout(
    priority_groups: List[str] = Query([]),
    db: Session = Depends(get_session),
):
    """
    Recommend exercises with dynamic set targets based on zoned fatigue.
    """
    if not priority_groups:
        return {
            "message": "No priority groups specified",
            "recommendations": [],
        }

    status = get_muscle_status_with_decay(db)
    recommendations = []

    for group in priority_groups:
        current_f = status.get(group, 0.0)

        # The Binary Cutoff Fix: Zoned Volume Calculation
        if current_f >= FATIGUE_LIMIT:
            # Zone: Fried (10.0+)
            recommendations.append(
                {
                    "warning": f"{group} is red-zoned ({current_f:.1f}/{FATIGUE_LIMIT}). Skip or do active recovery."
                }
            )
            continue

        elif current_f < 4.0:
            # Zone: Fresh (0.0 - 4.0)
            target_sets = 4
        elif current_f < 8.0:
            # Zone: Recovering (4.1 - 8.0)
            target_sets = 3
        else:
            # Zone: High Fatigue (8.1 - 9.9) - Tapering volume
            target_sets = 2

        # Fetch exercises where this group is primary
        exercises = db.exec(
            select(Exercise).where(Exercise.primary_muscle == group)
        ).all()

        # Attach the calculated target_sets to each exercise
        for ex in exercises:
            # .model_dump() converts the SQLModel to a standard dictionary
            ex_data = ex.model_dump()
            ex_data["target_sets"] = target_sets
            recommendations.append(ex_data)

    return {
        "priority_groups": priority_groups,
        "status": status,
        "recommendations": recommendations,
    }


@app.get("/workouts/history", tags=["History"])
def get_workout_history(
    db: Session = Depends(get_session),
    limit: int = Query(20, ge=1, le=100),
):
    """Get workout history (most recent first) with calculated stats."""
    sessions = db.exec(
        select(WorkoutSession)
        .where(WorkoutSession.status == "completed")
        .order_by(WorkoutSession.date.desc())
        .limit(limit)
    ).all()

    # Calculate the volume and sets for each session
    history_data = []
    for session in sessions:
        logs = db.exec(select(SetLog).where(SetLog.session_id == session.id)).all()
        total_volume = sum(log.reps * log.weight for log in logs)

        history_data.append(
            {
                "id": session.id,
                "date": session.date,
                "duration_minutes": session.duration_minutes,
                "total_sets": len(logs),
                "total_volume": round(total_volume, 2),
                "status": session.status,
                "planned_template": session.planned_template,
            }
        )

    return history_data


@app.get("/workouts/{session_id}", tags=["History"])
def get_workout_detail(
    session_id: int,
    db: Session = Depends(get_session),
):
    """Get detailed workout summary with all logs."""
    session = db.get(WorkoutSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    logs = db.exec(select(SetLog).where(SetLog.session_id == session_id)).all()

    # Calculate summary stats
    total_volume = sum(log.reps * log.weight for log in logs)
    exercises_used = len(set(log.exercise_id for log in logs))

    return {
        "id": session.id,
        "date": session.date,
        "duration_minutes": session.duration_minutes,
        "total_sets": len(logs),
        "total_volume": round(total_volume, 2),
        "exercises_count": exercises_used,
        "notes": session.notes,
        "logs": logs,
    }


@app.get("/analytics/volume", tags=["Analytics"])
def get_volume_trends(
    muscle_group: Optional[str] = None,
    days: int = Query(30, ge=1, le=365),
    db: Session = Depends(get_session),
):
    """
    Get volume data for the last N days.
    Returns total volume per workout day, optionally filtered by muscle group.
    """
    from datetime import timedelta

    cutoff_date = datetime.now() - timedelta(days=days)

    # Get all recent sessions
    sessions = db.exec(
        select(WorkoutSession)
        .where(
            (WorkoutSession.status == "completed")
            & (WorkoutSession.date >= cutoff_date)
        )
        .order_by(WorkoutSession.date.asc())
    ).all()

    volume_data = {}
    for session in sessions:
        logs = db.exec(select(SetLog).where(SetLog.session_id == session.id)).all()

        for log in logs:
            ex = db.get(Exercise, log.exercise_id)
            if not ex:
                continue

            # Filter by muscle if specified
            if muscle_group:
                if muscle_group not in (ex.primary_muscle, ex.secondary_muscle):
                    continue

            date_key = session.date.strftime("%Y-%m-%d")
            if date_key not in volume_data:
                volume_data[date_key] = 0.0
            volume_data[date_key] += log.reps * log.weight

    return {
        "muscle_group": muscle_group or "all",
        "days": days,
        "data": volume_data,
    }


@app.get("/analytics/fatigue-trend", tags=["Analytics"])
def get_fatigue_recovery(
    muscle_group: str,
    db: Session = Depends(get_session),
):
    """
    Get current fatigue state and recovery estimate for a muscle group.
    Shows how long until below FATIGUE_LIMIT.
    """
    state = db.get(MuscleState, muscle_group)
    if not state:
        return {
            "muscle_group": muscle_group,
            "fatigue": 0.0,
            "recovered": True,
        }

    current_f = get_decayed_fatigue(state)

    # Calculate hours until below fatigue limit
    if current_f > FATIGUE_LIMIT:
        # Solve: current_f * e^(-k*t) = FATIGUE_LIMIT for t
        # t = ln(current_f / FATIGUE_LIMIT) / k
        recovery_days = math.log(current_f / FATIGUE_LIMIT) / DECAY_K
        recovery_hours = recovery_days * 24
    else:
        recovery_hours = 0

    return {
        "muscle_group": muscle_group,
        "fatigue": round(current_f, 2),
        "limit": FATIGUE_LIMIT,
        "recovered": current_f < FATIGUE_LIMIT,
        "estimated_recovery_hours": round(max(0, recovery_hours), 1),
    }


# --- Health Check ---


@app.get("/health", tags=["System"])
def health_check():
    """Health check endpoint."""
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=5100, reload=True)
